---
language: python
python: "2.7"

before_install:
   # Make sure everything's up to date.
  - sudo apt-get update -qq
  - sudo apt-get install -qq python-apt python-pycurl git python-pip

install:
   # Install Ansible.
  - pip install ansible

script:
    - cd tests
    # 1st: check syntax
    - echo "***************************** SYNTAX CHECK test 1 (1) *****************************"
    - ansible-playbook -i local.ini test1.yml --syntax-check
    # 2nd:  Make sure we run the entire playbook
    - echo "***************************** RUN PLAY test 1 (2) *****************************"    
    - ansible-playbook -i local.ini test1.yml --sudo -vvvv
    # 3rd:  Make sure our playbook is idempotent 
    - echo "***************************** Idempotence test test 1 (3) *****************************"     
    - >
      ansible-playbook -i local.ini test1.yml --sudo -vvvv | tee ansible_output  
      | grep -q 'changed=0.*failed=0'
      && (echo 'Idempotence test: pass' && exit 0)
      || (echo 'Idempotence test: fail' && exit 1)

    # 1st: check syntax
    - echo "***************************** SYNTAX CHECK test 2 (1) *****************************"
    - ansible-playbook -i local.ini test2.yml --syntax-check
    # 2nd:  Make sure we run the entire playbook
    - echo "***************************** RUN PLAY test 2 (2) *****************************"
    - ansible-playbook -i local.ini test2.yml --sudo -vvvv
    # 3rd:  Make sure our playbook is idempotent
    - echo "***************************** Idempotence test test 2 (3) *****************************"
    - >
      ansible-playbook -i local.ini test2.yml --sudo -vvvv | tee ansible_output
      | grep -q 'changed=0.*failed=0'
      && (echo 'Idempotence test: pass' && exit 0)
      || (echo 'Idempotence test: fail' && exit 1)

    # 1st: check syntax
    - echo "***************************** SYNTAX CHECK test 3 (1) *****************************"
    - ansible-playbook -i local.ini test3.yml --syntax-check
    # 2nd:  Make sure we run the entire playbook
    - echo "***************************** RUN PLAY test 3 (2) *****************************"
    - ansible-playbook -i local.ini test3.yml --sudo -vvvv
    # 3rd:  Make sure our playbook is idempotent
    - echo "***************************** Idempotence test test 3 (3) *****************************"
    - >
      ansible-playbook -i local.ini test3.yml --sudo -vvvv | tee ansible_output
      | grep -q 'changed=0.*failed=0'
      && (echo 'Idempotence test: pass' && exit 0)
      || (echo 'Idempotence test: fail' && exit 1)

after_failure:
    - echo "******IdepotanceLog *******" 
    - sudo cat ansible_output
    - echo "******Syslog*******"
    - sudo cat /var/log/syslog
    - echo "******NerveLog*******" 
    - sudo cat /var/log/smartstack/nerve.log  
    - echo "******SerfLog*******"
    - sudo cat /var/log/smartstack/serf.log  
    - echo "******SyanpaseLog*******"
    - sudo cat /var/log/smartstack/synapse.log
    - echo "******AnsibleFacts*******"    
    - ansible -i 127.0.0.1, -m setup all -c local