---
- name : common | Create smartstack user
  user : 
    name="{{smartstack_user}}"
    shell="/sbin/nologin"
    home="{{smartstack_home}}"
    createhome="yes"

  # TODO: Remove me Left for backward compatibility 
- name: common | Install git 
  apt:
     name="git"
  when: smartstack_git_install

- name: common | Create base log directory
  file: 
   path="{{smartstack_base_log_dir}}"
   owner="{{smartstack_user}}"
   group="{{smartstack_user}}"
   mode=0755
   state=directory