---
# tasks file for ansible-smartstack

- name: nerv | Create synapse directories
  file: 
   path="{{ nerve_home }}"
   owner="{{ smartstack_user }}"
   group="{{ smartstack_user }}"
   mode=0755
   state=directory

- name: nerve | Get nerve from gi
  git:
      repo="{{nerve_repository}}"
      dest="{{nerve_install_dir}}"
      force="no"
      version="{{nerve_reference}}"
      accept_hostkey=true
  when: not smartstack_omnibus_install 
  sudo_user: "{{smartstack_user}}"

- name: nerve | Install nerve
  shell: bundle install --without development --frozen
  args:
    chdir: "{{ nerve_install_dir }}"
  environment: smartstack_env_variable
  register: nerve_bundle_install
  changed_when: nerve_bundle_install.stdout.find('Installing') != -1
  when: not smartstack_omnibus_install 
  sudo_user: "{{smartstack_user}}"

  #Maybe include in common only rather in synapse and nerve
- name: nerve | Include services variable file
  include_vars: "{{smartstack_services_files}}"
  when: smartstack_services_files is defined and smartstack_services_files

- name: nerve | Deploy configuration file
  template:
    src=nerve/nerve_config.json.j2
    dest="{{nerve_home}}/config.json"
    mode=0640
    owner="{{smartstack_user}}"
    group="{{smartstack_user}}"
  notify: restart nerve

- name: nerve | Deploy start script
  template:
    src=nerve/nerve_start.sh.j2
    dest="{{nerve_home}}/nerve_start.sh"
    mode=0755

- name: nerve | Configure nerve log rotation
  template:
    src=nerve/nerve_log_rotation.j2
    dest=/etc/logrotate.d/nerve

- name: nerve | Deploy init.d script
  template:
    src=nerve/nerve_init.sh.j2
    dest="/etc/init.d/nerve"
    mode=0755

- name: nerve | Ensure nerve is running
  service: 
    name=nerve
    state=started
    enabled=true